import 'package:blue_thermal_printer/blue_thermal_printer.dart'; import 'package:intl/intl.dart';
class ReceiptService { final BlueThermalPrinter printer = BlueThermalPrinter.instance;
Future<void> printReceipt(Map sale) async { String date = DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now());
  await printer.printCustom("ShopSmart Tuckshop", 3, 1); await printer.printCustom(sale['address']?? "Harare, ZW", 1, 1); await printer.printCustom("Tel: ${sale['phone']?? '0772 123 456'}", 1, 1); await printer.printNewLine();
  await printer.printCustom("Receipt: ${sale['receipt_number']}", 1, 0); await printer.printCustom("Date: $date", 1, 0); await printer.printCustom("Cashier: ${sale['cashier']}", 1, 0); if(sale['customer']!= null) await printer.printCustom("Customer: ${sale['customer']}", 1, 0); await printer.printCustom("-----------------------------", 1, 0);
  for (var item in sale['items']) { String name = item['name'].toString().substring(0, item['name'].length > 12? 12 : item['name'].length); String line = name.padRight(12) + "${item['qty']}x".padLeft(4) + "\$${(item['qty'] * item['selling_price']).toStringAsFixed(2)}".padLeft(9); await printer.printCustom(line, 1, 0); }
  await printer.printCustom("-----------------------------", 1, 0); await printer.printCustom("SUBTOTAL:".padRight(20) + "\$${sale['subtotal'].toStringAsFixed(2)}".padLeft(8), 1, 0); await printer.printCustom("VAT 15.5%:".padRight(20) + "\$${sale['vat'].toStringAsFixed(2)}".padLeft(8), 1, 0); await printer.printCustom("TOTAL:".padRight(20) + "\$${sale['total'].toStringAsFixed(2)}".padLeft(8), 2, 0); await printer.printCustom("TENDERED:".padRight(20) + "\$${sale['amount_tendered'].toStringAsFixed(2)}".padLeft(8), 1, 0); await printer.printCustom("CHANGE:".padRight(20) + "\$${sale['change'].toStringAsFixed(2)}".padLeft(8), 1, 0);
  await printer.printNewLine(); await printer.printCustom("PAYMENT: ${sale['payment_method']}", 1, 1); if(sale['payment_ref']!= null) await printer.printCustom("Ref: ${sale['payment_ref']}", 1, 1); if(sale['payment_method'] == "ECOCASH") await printer.printCustom("Till: ${sale['ecocash_till']}", 1, 1); if(sale['points']!= null) await printer.printCustom("Points Earned: ${sale['points'].toStringAsFixed(0)}", 1, 1);
  await printer.printCustom("**ZIMRA COMPLIANT RECORD**", 1, 1); await printer.printCustom("Thank you! Come Again", 1, 1); await printer.printNewLine(); await printer.paperCut(); }}
